# Autogenerated seed data for FIFA World Cup 2026
# All dates are in UTC (coordinated universal time)
# Source: official FIFA match schedule / football-data.org API
import datetime
from .models import Partido

seed_matches = [
    # ── FECHA 1 ──────────────────────────────────────────────────────
    # Jun 11 – Mexico City (CDT = UTC-5)
    Partido(id_partido=1,  fecha=datetime.datetime(2026, 6, 11, 19, 0), fase='Fecha 1', equipo_local='México',          equipo_visitante='Sudáfrica'),
    # Jun 12 – Los Angeles (PDT = UTC-7)
    Partido(id_partido=2,  fecha=datetime.datetime(2026, 6, 12, 2,  0), fase='Fecha 1', equipo_local='Corea del Sur',  equipo_visitante='República Checa'),
    # Jun 12 – Toronto (EDT = UTC-4)
    Partido(id_partido=3,  fecha=datetime.datetime(2026, 6, 12, 19, 0), fase='Fecha 1', equipo_local='Canadá',          equipo_visitante='Bosnia y Herzegovina'),
    # Jun 12 – Kansas City (CDT = UTC-5)
    Partido(id_partido=4,  fecha=datetime.datetime(2026, 6, 13, 1,  0), fase='Fecha 1', equipo_local='Estados Unidos',  equipo_visitante='Paraguay'),
    # Jun 13 – Mexico City (CDT = UTC-5)
    Partido(id_partido=5,  fecha=datetime.datetime(2026, 6, 13, 19, 0), fase='Fecha 1', equipo_local='Qatar',           equipo_visitante='Suiza'),
    # Jun 13 – Miami (EDT = UTC-4)
    Partido(id_partido=6,  fecha=datetime.datetime(2026, 6, 13, 22, 0), fase='Fecha 1', equipo_local='Brasil',          equipo_visitante='Marruecos'),
    # Jun 13 – Los Angeles (PDT = UTC-7)
    Partido(id_partido=7,  fecha=datetime.datetime(2026, 6, 14, 1,  0), fase='Fecha 1', equipo_local='Haití',           equipo_visitante='Escocia'),
    # Jun 13 – San Francisco (PDT = UTC-7) — 21:00 PDT = 04:00 UTC Jun 14
    Partido(id_partido=8,  fecha=datetime.datetime(2026, 6, 14, 4,  0), fase='Fecha 1', equipo_local='Australia',       equipo_visitante='Turquía'),
    # Jun 14 – Dallas (CDT = UTC-5)
    Partido(id_partido=9,  fecha=datetime.datetime(2026, 6, 14, 17, 0), fase='Fecha 1', equipo_local='Alemania',        equipo_visitante='Curazao'),
    # Jun 14 – New York (EDT = UTC-4)
    Partido(id_partido=10, fecha=datetime.datetime(2026, 6, 14, 20, 0), fase='Fecha 1', equipo_local='Países Bajos',    equipo_visitante='Japón'),
    # Jun 14 – Atlanta (EDT = UTC-4)
    Partido(id_partido=11, fecha=datetime.datetime(2026, 6, 14, 23, 0), fase='Fecha 1', equipo_local='Costa de Marfil', equipo_visitante='Ecuador'),
    # Jun 14 – Seattle (PDT = UTC-7) — 19:00 PDT = 02:00 UTC Jun 15
    Partido(id_partido=12, fecha=datetime.datetime(2026, 6, 15, 2,  0), fase='Fecha 1', equipo_local='Suecia',          equipo_visitante='Túnez'),
    # Jun 15 – Miami (EDT = UTC-4)
    Partido(id_partido=13, fecha=datetime.datetime(2026, 6, 15, 16, 0), fase='Fecha 1', equipo_local='España',          equipo_visitante='Cabo Verde'),
    # Jun 15 – Atlanta (EDT = UTC-4)
    Partido(id_partido=14, fecha=datetime.datetime(2026, 6, 15, 19, 0), fase='Fecha 1', equipo_local='Bélgica',         equipo_visitante='Egipto'),
    # Jun 15 – Miami (EDT = UTC-4)
    Partido(id_partido=15, fecha=datetime.datetime(2026, 6, 15, 22, 0), fase='Fecha 1', equipo_local='Arabia Saudita',  equipo_visitante='Uruguay'),
    # Jun 15 – Los Angeles (PDT = UTC-7) — 18:00 PDT = 01:00 UTC Jun 16
    Partido(id_partido=16, fecha=datetime.datetime(2026, 6, 16, 1,  0), fase='Fecha 1', equipo_local='Irán',            equipo_visitante='Nueva Zelanda'),
    # Jun 16 – New York (EDT = UTC-4)
    Partido(id_partido=17, fecha=datetime.datetime(2026, 6, 16, 19, 0), fase='Fecha 1', equipo_local='Francia',         equipo_visitante='Senegal'),
    # Jun 16 – Boston (EDT = UTC-4)
    Partido(id_partido=18, fecha=datetime.datetime(2026, 6, 16, 22, 0), fase='Fecha 1', equipo_local='Irak',            equipo_visitante='Noruega'),
    # Jun 16 – Kansas City (CDT = UTC-5) — 20:00 CDT = 01:00 UTC Jun 17
    Partido(id_partido=19, fecha=datetime.datetime(2026, 6, 17, 1,  0), fase='Fecha 1', equipo_local='Argentina',       equipo_visitante='Argelia'),
    # Jun 16 – San Francisco (PDT = UTC-7) — 21:00 PDT = 04:00 UTC Jun 17
    Partido(id_partido=20, fecha=datetime.datetime(2026, 6, 17, 4,  0), fase='Fecha 1', equipo_local='Austria',         equipo_visitante='Jordania'),
    # Jun 17 – Houston (CDT = UTC-5)
    Partido(id_partido=21, fecha=datetime.datetime(2026, 6, 17, 17, 0), fase='Fecha 1', equipo_local='Portugal',        equipo_visitante='Congo'),
    # Jun 17 – Dallas (CDT = UTC-5)
    Partido(id_partido=22, fecha=datetime.datetime(2026, 6, 17, 20, 0), fase='Fecha 1', equipo_local='Inglaterra',      equipo_visitante='Croacia'),
    # Jun 17 – Toronto (EDT = UTC-4)
    Partido(id_partido=23, fecha=datetime.datetime(2026, 6, 17, 23, 0), fase='Fecha 1', equipo_local='Ghana',           equipo_visitante='Panamá'),
    # Jun 17 – Mexico City (CDT = UTC-5) — 21:00 CDT = 02:00 UTC Jun 18
    Partido(id_partido=24, fecha=datetime.datetime(2026, 6, 18, 2,  0), fase='Fecha 1', equipo_local='Uzbekistán',      equipo_visitante='Colombia'),

    # ── FECHA 2 ──────────────────────────────────────────────────────
    # Jun 18
    Partido(id_partido=25, fecha=datetime.datetime(2026, 6, 18, 22, 0), fase='Fecha 2', equipo_local='México',                 equipo_visitante='Corea del Sur'),
    Partido(id_partido=26, fecha=datetime.datetime(2026, 6, 18, 16, 0), fase='Fecha 2', equipo_local='Sudáfrica',              equipo_visitante='República Checa'),
    Partido(id_partido=27, fecha=datetime.datetime(2026, 6, 18, 19, 0), fase='Fecha 2', equipo_local='Canadá',                 equipo_visitante='Qatar'),
    Partido(id_partido=28, fecha=datetime.datetime(2026, 6, 18, 22, 0), fase='Fecha 2', equipo_local='Bosnia y Herzegovina',   equipo_visitante='Suiza'),
    # Jun 19
    Partido(id_partido=29, fecha=datetime.datetime(2026, 6, 19, 19, 0), fase='Fecha 2', equipo_local='Brasil',                 equipo_visitante='Haití'),
    Partido(id_partido=30, fecha=datetime.datetime(2026, 6, 19, 22, 0), fase='Fecha 2', equipo_local='Marruecos',              equipo_visitante='Escocia'),
    Partido(id_partido=31, fecha=datetime.datetime(2026, 6, 19, 22, 0), fase='Fecha 2', equipo_local='Estados Unidos',         equipo_visitante='Australia'),
    Partido(id_partido=32, fecha=datetime.datetime(2026, 6, 20, 1,  0), fase='Fecha 2', equipo_local='Paraguay',               equipo_visitante='Turquía'),
    # Jun 20
    Partido(id_partido=33, fecha=datetime.datetime(2026, 6, 20, 17, 0), fase='Fecha 2', equipo_local='Alemania',               equipo_visitante='Costa de Marfil'),
    Partido(id_partido=34, fecha=datetime.datetime(2026, 6, 20, 20, 0), fase='Fecha 2', equipo_local='Curazao',                equipo_visitante='Ecuador'),
    Partido(id_partido=35, fecha=datetime.datetime(2026, 6, 20, 20, 0), fase='Fecha 2', equipo_local='Bélgica',                equipo_visitante='Irán'),
    Partido(id_partido=36, fecha=datetime.datetime(2026, 6, 20, 23, 0), fase='Fecha 2', equipo_local='Egipto',                 equipo_visitante='Nueva Zelanda'),
    # Jun 21
    Partido(id_partido=37, fecha=datetime.datetime(2026, 6, 21, 17, 0), fase='Fecha 2', equipo_local='España',                 equipo_visitante='Arabia Saudita'),
    Partido(id_partido=38, fecha=datetime.datetime(2026, 6, 21, 20, 0), fase='Fecha 2', equipo_local='Cabo Verde',             equipo_visitante='Uruguay'),
    Partido(id_partido=39, fecha=datetime.datetime(2026, 6, 21, 20, 0), fase='Fecha 2', equipo_local='Francia',                equipo_visitante='Irak'),
    Partido(id_partido=40, fecha=datetime.datetime(2026, 6, 21, 23, 0), fase='Fecha 2', equipo_local='Senegal',                equipo_visitante='Noruega'),
    # Jun 22
    Partido(id_partido=41, fecha=datetime.datetime(2026, 6, 22, 17, 0), fase='Fecha 2', equipo_local='Argentina',              equipo_visitante='Austria'),
    Partido(id_partido=42, fecha=datetime.datetime(2026, 6, 22, 20, 0), fase='Fecha 2', equipo_local='Argelia',                equipo_visitante='Jordania'),
    Partido(id_partido=43, fecha=datetime.datetime(2026, 6, 22, 20, 0), fase='Fecha 2', equipo_local='Portugal',               equipo_visitante='Uzbekistán'),
    Partido(id_partido=44, fecha=datetime.datetime(2026, 6, 22, 23, 0), fase='Fecha 2', equipo_local='Congo',                  equipo_visitante='Colombia'),
    Partido(id_partido=45, fecha=datetime.datetime(2026, 6, 22, 23, 0), fase='Fecha 2', equipo_local='Inglaterra',             equipo_visitante='Ghana'),
    Partido(id_partido=46, fecha=datetime.datetime(2026, 6, 23, 2,  0), fase='Fecha 2', equipo_local='Croacia',                equipo_visitante='Panamá'),
    Partido(id_partido=47, fecha=datetime.datetime(2026, 6, 22, 20, 0), fase='Fecha 2', equipo_local='Países Bajos',           equipo_visitante='Suecia'),
    Partido(id_partido=48, fecha=datetime.datetime(2026, 6, 22, 23, 0), fase='Fecha 2', equipo_local='Japón',                  equipo_visitante='Túnez'),

    # ── FECHA 3 ──────────────────────────────────────────────────────
    Partido(id_partido=49, fecha=datetime.datetime(2026, 6, 23, 19, 0), fase='Fecha 3', equipo_local='República Checa',        equipo_visitante='México'),
    Partido(id_partido=50, fecha=datetime.datetime(2026, 6, 23, 19, 0), fase='Fecha 3', equipo_local='Sudáfrica',              equipo_visitante='Corea del Sur'),
    Partido(id_partido=51, fecha=datetime.datetime(2026, 6, 24, 0,  0), fase='Fecha 3', equipo_local='Suiza',                  equipo_visitante='Canadá'),
    Partido(id_partido=52, fecha=datetime.datetime(2026, 6, 24, 0,  0), fase='Fecha 3', equipo_local='Bosnia y Herzegovina',   equipo_visitante='Qatar'),
    Partido(id_partido=53, fecha=datetime.datetime(2026, 6, 24, 19, 0), fase='Fecha 3', equipo_local='Escocia',                equipo_visitante='Brasil'),
    Partido(id_partido=54, fecha=datetime.datetime(2026, 6, 24, 19, 0), fase='Fecha 3', equipo_local='Marruecos',              equipo_visitante='Haití'),
    Partido(id_partido=55, fecha=datetime.datetime(2026, 6, 25, 0,  0), fase='Fecha 3', equipo_local='Turquía',                equipo_visitante='Estados Unidos'),
    Partido(id_partido=56, fecha=datetime.datetime(2026, 6, 25, 0,  0), fase='Fecha 3', equipo_local='Paraguay',               equipo_visitante='Australia'),
    Partido(id_partido=57, fecha=datetime.datetime(2026, 6, 25, 19, 0), fase='Fecha 3', equipo_local='Ecuador',                equipo_visitante='Alemania'),
    Partido(id_partido=58, fecha=datetime.datetime(2026, 6, 25, 19, 0), fase='Fecha 3', equipo_local='Curazao',                equipo_visitante='Costa de Marfil'),
    Partido(id_partido=59, fecha=datetime.datetime(2026, 6, 26, 0,  0), fase='Fecha 3', equipo_local='Egipto',                 equipo_visitante='Irán'),
    Partido(id_partido=60, fecha=datetime.datetime(2026, 6, 26, 0,  0), fase='Fecha 3', equipo_local='Bélgica',                equipo_visitante='Nueva Zelanda'),
    Partido(id_partido=61, fecha=datetime.datetime(2026, 6, 26, 19, 0), fase='Fecha 3', equipo_local='España',                 equipo_visitante='Uruguay'),
    Partido(id_partido=62, fecha=datetime.datetime(2026, 6, 26, 19, 0), fase='Fecha 3', equipo_local='Cabo Verde',             equipo_visitante='Arabia Saudita'),
    Partido(id_partido=63, fecha=datetime.datetime(2026, 6, 27, 0,  0), fase='Fecha 3', equipo_local='Noruega',                equipo_visitante='Francia'),
    Partido(id_partido=64, fecha=datetime.datetime(2026, 6, 27, 0,  0), fase='Fecha 3', equipo_local='Senegal',                equipo_visitante='Irak'),
    Partido(id_partido=65, fecha=datetime.datetime(2026, 6, 27, 19, 0), fase='Fecha 3', equipo_local='Jordania',               equipo_visitante='Argentina'),
    Partido(id_partido=66, fecha=datetime.datetime(2026, 6, 27, 19, 0), fase='Fecha 3', equipo_local='Argelia',                equipo_visitante='Austria'),
    Partido(id_partido=67, fecha=datetime.datetime(2026, 6, 27, 22, 0), fase='Fecha 3', equipo_local='Inglaterra',             equipo_visitante='Panamá'),
    Partido(id_partido=68, fecha=datetime.datetime(2026, 6, 27, 22, 0), fase='Fecha 3', equipo_local='Croacia',                equipo_visitante='Ghana'),
    Partido(id_partido=69, fecha=datetime.datetime(2026, 6, 28, 1,  0), fase='Fecha 3', equipo_local='Portugal',               equipo_visitante='Colombia'),
    Partido(id_partido=70, fecha=datetime.datetime(2026, 6, 28, 1,  0), fase='Fecha 3', equipo_local='Congo',                  equipo_visitante='Uzbekistán'),
    Partido(id_partido=71, fecha=datetime.datetime(2026, 6, 27, 16, 0), fase='Fecha 3', equipo_local='Túnez',                  equipo_visitante='Países Bajos'),
    Partido(id_partido=72, fecha=datetime.datetime(2026, 6, 27, 16, 0), fase='Fecha 3', equipo_local='Japón',                  equipo_visitante='Suecia'),

    # ── DIECISEISAVOS DE FINAL ────────────────────────────────────────
    Partido(id_partido=73,  fecha=datetime.datetime(2026, 7, 2,  16, 0), fase='Dieciseisavos de Final', equipo_local='1A',              equipo_visitante='2B'),
    Partido(id_partido=74,  fecha=datetime.datetime(2026, 7, 2,  19, 0), fase='Dieciseisavos de Final', equipo_local='1C',              equipo_visitante='2D'),
    Partido(id_partido=75,  fecha=datetime.datetime(2026, 7, 2,  22, 0), fase='Dieciseisavos de Final', equipo_local='1E',              equipo_visitante='2F'),
    Partido(id_partido=76,  fecha=datetime.datetime(2026, 7, 3,  1,  0), fase='Dieciseisavos de Final', equipo_local='1G',              equipo_visitante='2H'),
    Partido(id_partido=77,  fecha=datetime.datetime(2026, 7, 3,  16, 0), fase='Dieciseisavos de Final', equipo_local='1I',              equipo_visitante='2J'),
    Partido(id_partido=78,  fecha=datetime.datetime(2026, 7, 3,  19, 0), fase='Dieciseisavos de Final', equipo_local='1K',              equipo_visitante='2L'),
    Partido(id_partido=79,  fecha=datetime.datetime(2026, 7, 3,  22, 0), fase='Dieciseisavos de Final', equipo_local='1B',              equipo_visitante='2A'),
    Partido(id_partido=80,  fecha=datetime.datetime(2026, 7, 4,  1,  0), fase='Dieciseisavos de Final', equipo_local='1D',              equipo_visitante='2C'),
    Partido(id_partido=81,  fecha=datetime.datetime(2026, 7, 4,  16, 0), fase='Dieciseisavos de Final', equipo_local='1F',              equipo_visitante='2E'),
    Partido(id_partido=82,  fecha=datetime.datetime(2026, 7, 4,  19, 0), fase='Dieciseisavos de Final', equipo_local='1H',              equipo_visitante='2G'),
    Partido(id_partido=83,  fecha=datetime.datetime(2026, 7, 4,  22, 0), fase='Dieciseisavos de Final', equipo_local='1J',              equipo_visitante='2I'),
    Partido(id_partido=84,  fecha=datetime.datetime(2026, 7, 5,  1,  0), fase='Dieciseisavos de Final', equipo_local='1L',              equipo_visitante='2K'),
    Partido(id_partido=85,  fecha=datetime.datetime(2026, 7, 5,  16, 0), fase='Dieciseisavos de Final', equipo_local='Mejor 3ro A/B/C', equipo_visitante='Mejor 3ro D/E/F'),
    Partido(id_partido=86,  fecha=datetime.datetime(2026, 7, 5,  19, 0), fase='Dieciseisavos de Final', equipo_local='Mejor 3ro G/H/I', equipo_visitante='Mejor 3ro J/K/L'),
    Partido(id_partido=87,  fecha=datetime.datetime(2026, 7, 5,  22, 0), fase='Dieciseisavos de Final', equipo_local='Mejor 3ro A/E/I', equipo_visitante='Mejor 3ro B/F/J'),
    Partido(id_partido=88,  fecha=datetime.datetime(2026, 7, 6,  1,  0), fase='Dieciseisavos de Final', equipo_local='Mejor 3ro C/G/K', equipo_visitante='Mejor 3ro D/H/L'),

    # ── OCTAVOS DE FINAL ─────────────────────────────────────────────
    Partido(id_partido=89,  fecha=datetime.datetime(2026, 7, 7,  19, 0), fase='Octavos de Final', equipo_local='Ganador Partido 73', equipo_visitante='Ganador Partido 74'),
    Partido(id_partido=90,  fecha=datetime.datetime(2026, 7, 8,  0,  0), fase='Octavos de Final', equipo_local='Ganador Partido 75', equipo_visitante='Ganador Partido 76'),
    Partido(id_partido=91,  fecha=datetime.datetime(2026, 7, 8,  19, 0), fase='Octavos de Final', equipo_local='Ganador Partido 77', equipo_visitante='Ganador Partido 78'),
    Partido(id_partido=92,  fecha=datetime.datetime(2026, 7, 9,  0,  0), fase='Octavos de Final', equipo_local='Ganador Partido 79', equipo_visitante='Ganador Partido 80'),
    Partido(id_partido=93,  fecha=datetime.datetime(2026, 7, 9,  19, 0), fase='Octavos de Final', equipo_local='Ganador Partido 81', equipo_visitante='Ganador Partido 82'),
    Partido(id_partido=94,  fecha=datetime.datetime(2026, 7, 10, 0,  0), fase='Octavos de Final', equipo_local='Ganador Partido 83', equipo_visitante='Ganador Partido 84'),
    Partido(id_partido=95,  fecha=datetime.datetime(2026, 7, 10, 19, 0), fase='Octavos de Final', equipo_local='Ganador Partido 85', equipo_visitante='Ganador Partido 86'),
    Partido(id_partido=96,  fecha=datetime.datetime(2026, 7, 11, 0,  0), fase='Octavos de Final', equipo_local='Ganador Partido 87', equipo_visitante='Ganador Partido 88'),

    # ── CUARTOS DE FINAL ─────────────────────────────────────────────
    Partido(id_partido=97,  fecha=datetime.datetime(2026, 7, 12, 19, 0), fase='Cuartos de Final', equipo_local='Ganador Partido 89', equipo_visitante='Ganador Partido 90'),
    Partido(id_partido=98,  fecha=datetime.datetime(2026, 7, 13, 0,  0), fase='Cuartos de Final', equipo_local='Ganador Partido 91', equipo_visitante='Ganador Partido 92'),
    Partido(id_partido=99,  fecha=datetime.datetime(2026, 7, 13, 19, 0), fase='Cuartos de Final', equipo_local='Ganador Partido 93', equipo_visitante='Ganador Partido 94'),
    Partido(id_partido=100, fecha=datetime.datetime(2026, 7, 14, 0,  0), fase='Cuartos de Final', equipo_local='Ganador Partido 95', equipo_visitante='Ganador Partido 96'),

    # ── SEMIFINALES ───────────────────────────────────────────────────
    Partido(id_partido=101, fecha=datetime.datetime(2026, 7, 16, 0,  0), fase='Semifinal', equipo_local='Ganador Partido 97',  equipo_visitante='Ganador Partido 98'),
    Partido(id_partido=102, fecha=datetime.datetime(2026, 7, 17, 0,  0), fase='Semifinal', equipo_local='Ganador Partido 99',  equipo_visitante='Ganador Partido 100'),

    # ── FINAL ─────────────────────────────────────────────────────────
    Partido(id_partido=103, fecha=datetime.datetime(2026, 7, 19, 19, 0), fase='Final',    equipo_local='Ganador Partido 101', equipo_visitante='Ganador Partido 102'),
]
